volumes:
  mongodb_data:
  redis_data:
    driver: local

networks:
  rabbit_connection_net:
    name: scalable-commerce-net
    external: true
  api-net:
    driver: bridge

services:
  database:
    image: mongo:8.0.13-rc1
    container_name: database-auth
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - api-net

  redis:
      image: redis:7.2
      container_name: redis-auth
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1
      volumes:
        - redis_data:/data
      networks:
        - api-net
  api:
    container_name: scalable-e-commerce-api
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - database
    restart: always
    networks:
      - rabbit_connection_net
      - api-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    develop:
      watch:
        - action: rebuild
          path: .