services:

  database:
    image: mongo:8.0.13-rc1
    container_name: database-auth
    restart: always
    networks:
      - rabbit_connection_net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE="auth"
      - MONGO_DB_HOST=${MONGO_DB_HOST}
    volumes:
      - mongodb_data:/data/db
  api:
    container_name: scalable-e-commerce-api
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - database
    restart: always
    networks:
      - rabbit_connection_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_INITDB_DATABASE="auth"
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    links:
      - database
    user: root
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  mongodb_data:
    driver: local

networks:
  rabbit_connection_net:
    name: scalable-commerce-net
    external: true