volumes:
  postgres_data:
  redis_data:
    driver: local

networks:
  rabbit_connection_net:
    name: scalable-commerce-net
    external: true
  api-net:
    driver: bridge

services:
  database:
    image: postgres:18-alpine
    container_name: database-users
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/data/db
    networks:
      - api-net

  redis:
      image: redis:7.2
      container_name: redis-users
      restart: always
      ports:
        - "6380:6379"
      command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1
      volumes:
        - redis_data:/data
      networks:
      - api-net
  api:
    container_name: scalable-e-commerce-users-api
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - database
    restart: always
    networks:
      - rabbit_connection_net
      - api-net
    develop:
      watch:
        - action: rebuild
          path: .